#!/usr/bin/env python3
import sys, os

MOOSE_DIR = os.path.abspath(os.environ.get('MOOSE_DIR', os.path.join(os.path.dirname(__file__), '..', 'moose')))
if os.path.exists(os.path.abspath(os.path.join('moose', 'framework', 'Makefile'))):
  MOOSE_DIR = os.path.abspath('moose')
MOOSE_DIR = os.environ.get('MOOSE_DIR', MOOSE_DIR)

sys.path.append(os.path.join(MOOSE_DIR, 'python'))

print('MOOSE directory: ', MOOSE_DIR)

os.environ['PATH'] = os.path.join(MOOSE_DIR, 'test') + os.pathsep + os.environ['PATH']

from TestHarness import TestHarness
TestHarness.buildAndRun(sys.argv, 'moose_test', MOOSE_DIR)
