#!/usr/bin/env python3
import sys, os

MOOSE_DIR = os.path.abspath(os.environ.get('MOOSE_DIR', os.path.join(os.path.dirname(__file__), '..', 'moose')))
if os.path.exists(os.path.abspath(os.path.join('moose', 'framework', 'Makefile'))):
  MOOSE_DIR = os.path.abspath('moose')
MOOSE_DIR = os.environ.get('MOOSE_DIR', MOOSE_DIR)

sys.path.append(os.path.join(MOOSE_DIR, 'python'))

test_executable_path = os.path.join(MOOSE_DIR, 'test', 'moose_test')
print('Test executable path: ', test_executable_path)

from TestHarness import TestHarness
TestHarness.buildAndRun(sys.argv, test_executable_path, MOOSE_DIR)
